name: 01 - Tests simples Maven

on:
  workflow_dispatch:

jobs:
  test:
    name: Exécuter les tests Maven
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 00_rendu_exercices/exercice13

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          cache-dependency-path: 00_rendu_exercices/exercice13/pom.xml

      - name: Vérifier la version de Java
        run: java -version

      - name: Vérifier la version de Maven
        run: mvn -version

      - name: Lancer les tests
        run: mvn clean test
